# Generated by Django 5.0 on 2023-12-31 05:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên danh mục')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': '1 - Danh mục sản phẩm',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Made',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='Made_image', verbose_name='Ảnh đại diện')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên quốc gia')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': '3 - Quốc gia sản xuất',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Trademark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='Trademark_image', verbose_name='Ảnh đại diện')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên thương hiệu')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': '2 - Thương hiệu',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Tên khách hàng')),
                ('Phone', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Số điện thoại khách hàng')),
                ('Address', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Địa chỉ khách hàng')),
                ('Birthday', models.DateField(blank=True, null=True, verbose_name='Ngày sinh khách hàng')),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='User_image')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Quản lý tài khoản Đăng nhập',
                'ordering': ['id'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tổng số lượng')),
                ('Total_money', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tổng giá trị')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Cart_User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '7 - Giỏ hàng của khách hàng',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Oder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã đơn hàng')),
                ('Total_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tổng số lượng')),
                ('Total_money', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tổng giá trị')),
                ('Status', models.CharField(blank=True, default='Đang chờ xác nhận', max_length=100, null=True, verbose_name='Trạng thái')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Oder_User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '9 - Đơn hàng hàng của khách hàng',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='Product_image', verbose_name='Ảnh đại diện')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên sản phẩm')),
                ('Code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã sản phẩm')),
                ('Price', models.IntegerField(blank=True, null=True, verbose_name='Giá sản phẩm')),
                ('Percent_discount', models.IntegerField(blank=True, default=10, null=True, verbose_name='Phần trăm giảm giá (%)')),
                ('Price_has_decreased', models.IntegerField(blank=True, default=10, null=True, verbose_name='Giá sau khi giảm')),
                ('Describe', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('Guarantee', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bảo hành')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Category', to='web_ai.category')),
                ('Made', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products_Made', to='web_ai.made')),
                ('Trademark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Trademark', to='web_ai.trademark')),
            ],
            options={
                'verbose_name_plural': '4 - Sản phẩm bán',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Oder_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField(blank=True, null=True, verbose_name='Số lượng mua')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Oder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Oder_detail_Oder', to='web_ai.oder')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Oder_detail_Product', to='web_ai.product')),
            ],
            options={
                'verbose_name_plural': '91 - Chi tiết các mặt hàng trong đơn hàng',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cart_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField(blank=True, default=1, null=True, verbose_name='Số lượng mua')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cart_detail_Cart', to='web_ai.cart')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cart_detail_Product', to='web_ai.product')),
            ],
            options={
                'verbose_name_plural': '8 - Các đơn hàng được thêm vào giỏ hàng',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='Số lượng')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_ai.product')),
            ],
            options={
                'verbose_name_plural': '5 - Kho hàng',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Goods_received_note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã phiếu')),
                ('input', models.IntegerField(blank=True, null=True, verbose_name='Số lượng nhập')),
                ('Total', models.IntegerField(blank=True, null=True, verbose_name='Giá trị đơn nhập')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Goods_received_note_Product', to='web_ai.product')),
                ('Stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Goods_received_note_Stock', to='web_ai.stock')),
            ],
            options={
                'verbose_name_plural': '6 - Phiếu nhập hàng',
                'ordering': ['id'],
            },
        ),
    ]
